baseurl = "http://dplesca.github.io/purehugo/"
languageCode = "en-us"
title = "Juho Timonen"
theme = "purehugo"
Paginate = 10
disqusShortname = "xxxx"

[params]
  twitterName = "TimonenJuho"
  githubName = "jtimonen"
  linkedinName = "jtimo"
  description = "Doctoral Candidate \nComputer Science \nAalto University"
  google_analytics = "UA-xxxxxx-xx"

