title = "Juho Timonen"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Doctoral Candidate, Department of Computer Science, Aalto University"
  facebook = ""
  twitter = "https://twitter.com/TimonenJuho"
  instagram = ""
  youtube = ""
  github = "https://github.com/jtimonen/"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/jtimo/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
  body_classes = "avenir bg-near-white"
