title = "Juho Timonen"
baseURL = "https://example.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Espoo, Finland"
email = "timse@iki.fi"
favicon = "/favicon.ico"
firstName = "Juho"
lastName = "Timonen"
profileImage = ""
showEducation = true
showExperience = false
showOpenSource = false
showProjects = false
showPublications = true
showQr = false
showSkills = false

[params.google]

[params.google.analytics]
trackerID = ""

[[params.handles]]
link = "https://www.linkedin.com/in/jtimonen/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/jtimonen/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"

